kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdmin
  namespace: database # TODO: Re-run this file with other necessary ns
  # namespace: backup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","update","delete"]

# target all resources with full access
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdminBinding
  namespace: database # TODO: Re-run this file with other necessary ns, match with role above
  # namespace: backup
subjects:
  - kind: User
    name: Jessica
# note: this is case sensitive
roleRef:
  kind: Role
  name: DBAdmin
  apiGroup: rbac.authorization.k8s.io